export interface AdCategory {
  name: string;
  subCategories: AdSubCategory[];
}

export interface AdSubCategory {
  name: string;
  tags: AdTag[];
}

export interface AdTag {
  name: string;
}

export const categories: AdCategory[] = [
  {
    name: "Teaching & Tutoring",
    subCategories: [
      {
        name: "Language lessons",
        tags: [
          { name: "Arabic" },
          { name: "Chinese" },
          { name: "Dutch" },
          { name: "English" },
          { name: "French" },
          { name: "German" },
          { name: "Hindi" },
          { name: "Italian" },
          { name: "Korean" },
          { name: "Japanese" },
          { name: "Polish" },
          { name: "Portuguese" },
          { name: "Russian" },
          { name: "Spanish" },
          { name: "Thai" },
          { name: "Turkish" },
          { name: "Ukrainian" },
          { name: "Business English" },
          { name: "Business German" },
          { name: "British English" },
          { name: "Medical English" },
          { name: "Medical German" },
          { name: "Conversation" },
          { name: "Grammar" },
          { name: "Spelling" },
          { name: "Test Preparation" },
          { name: "FIRST" },
          { name: "IELTS" },
          { name: "TOEFL" },
          { name: "Beginner" },
          { name: "Intermediate" },
          { name: "Advanced" },
          { name: "Technical English" },
          { name: "Research English" },
          { name: "Latin" },
          { name: "Greek" },
        ],
      },
      {
        name: "Music Lessons",
        tags: [
          { name: "Bass" },
          { name: "Drums" },
          { name: "Guitar" },
          { name: "Piano" },
          { name: "Viola" },
          { name: "Violin" },
          { name: "Ukelele" },
          { name: "Music composition" },
          { name: "Singing" },
          { name: "Vocal teacher" },
          { name: "Orchestra" },
          { name: "Lyric" },
        ],
      },
      {
        name: "Tutoring Services",
        tags: [
          { name: "Accounting" },
          { name: "Acting skills" },
          { name: "Algebra" },
          { name: "Art" },
          { name: "Biology" },
          { name: "Business analytics" },
          { name: "Business & Management" },
          { name: "Calculus" },
          { name: "Chemistry" },
          { name: "Computer science" },
          { name: "Data science" },
          { name: "Drawing" },
          { name: "Economics" },
          { name: "Geometry" },
          { name: "Geography" },
          { name: "Graphic Design" },
          { name: "Finance" },
          { name: "History" },
          { name: "Homework help" },
          { name: "Law" },
          { name: "Literature" },
          { name: "Math" },
          { name: "Philosophy" },
          { name: "Photography" },
          { name: "Physics" },
          { name: "Product Management" },
          { name: "Psychology" },
          { name: "Public speaking" },
          { name: "Sale & Pricing" },
          { name: "Science" },
          { name: "Sculpting" },
          { name: "SEM" },
          { name: "SEO" },
          { name: "Special Needs tutor" },
          { name: "Sociology" },
          { name: "Statistics" },
          { name: "Writing Online" },
          { name: "Pre -K" },
          { name: "Elementary School" },
          { name: "Middle School" },
          { name: "High School" },
          { name: "College" },
          { name: "Post college" },
          { name: "Gymnasium" },
          { name: "Realschule" },
          { name: "Grundschule" },
          { name: "Hauptschule" },
          { name: "Hochschule" },
          { name: "Universität" },
          { name: "Fachhochschule" },
          { name: "Abitur" },
          { name: "Azubi" },
        ],
      },
    ],
  },
  {
    name: "Beauty, Fitnes & Wellness",
    subCategories: [
      {
        name: "Beauty",
        tags: [
          { name: "Barber" },
          { name: "Beauty" },
          { name: "Blowouts" },
          { name: "Braids" },
          { name: "Color" },
          { name: "Eyebrows & Lashes" },
          { name: "Hair" },
          { name: "Hair extensions" },
          { name: "Hair removal" },
          { name: "Make up" },
          { name: "Manicure" },
          { name: "Microblading" },
          { name: "Nail" },
          { name: "Skincare" },
          { name: "Pedicure" },
          { name: "Spray tan" },
          { name: "Tanning" },
          { name: "Tatto & Piercing" },
          { name: "Updos" },
          { name: "Waxing" },
          { name: "Wedding trial" },
          { name: "Kids haircut" },
          { name: "Men haircut" },
          { name: "Women haircut" },
        ],
      },
      {
        name: "Fitness",
        tags: [
          { name: "Acrobatics" },
          { name: "Aerial" },
          { name: "Aerobic fitness" },
          { name: "Ballet" },
          { name: "Ballroom" },
          { name: "Barre class" },
          { name: "Bodyweight" },
          { name: "Bootcamp" },
          { name: "Boxing" },
          { name: "Cardio" },
          { name: "Circuit training" },
          { name: "Contemporary" },
          { name: "Crossfit" },
          { name: "Cycling" },
          { name: "Dance" },
          { name: "Flexibility" },
          { name: "Football" },
          { name: "Gym" },
          { name: "HIIT" },
          { name: "Hip hop" },
          { name: "Jazz" },
          { name: "Kickboxing" },
          { name: "Martial arts" },
          { name: "Outdoor" },
          { name: "Personal trainer" },
          { name: "Pilates" },
          { name: "Pole fitness" },
          { name: "Prenatal fitness" },
          { name: "Running" },
          { name: "Tennis" },
          { name: "Trap" },
          { name: "Salsa" },
          { name: "Soccer" },
          { name: "Spinning" },
          { name: "Stretching" },
          { name: "Swing" },
          { name: "TRX class" },
          { name: "Tango" },
          { name: "Weight training" },
          { name: "Yoga" },
          { name: "Zumba" },
          { name: "Swimming" },
          { name: "Bouldern" },
          { name: "Climbing" },
        ],
      },
      {
        name: "Wellness",
        tags: [
          { name: "Acupuncture" },
          { name: " Coaching" },
          { name: " Massage" },
          { name: "Meditation" },
          { name: "Mindfulness" },
          { name: "Nutrition" },
          { name: "Spa" },
          { name: "Reflexology" },
          { name: "Reiki" },
          { name: "Holistic Health" },
        ],
      },
    ],
  },
  {
    name: "Caregiving",
    subCategories: [
      {
        name: "Childcare",
        tags: [
          { name: "Companionship" },
          { name: "CPR training" },
          { name: "Errands" },
          { name: "First aid training" },
          { name: "Homework help" },
          { name: "Infant care" },
          { name: "Light housekeeping" },
          { name: " Live-in care" },
          { name: "Live-out care" },
          { name: "Meal preparation" },
          { name: "Mobility support" },
          { name: "Newborn care" },
          { name: "Overnight sitting" },
          { name: "Personal care (e.g washing, dressing)" },
          { name: "Pick up / Drop off" },
          { name: " Shopping" },
          { name: " Virtual Care" },
        ],
      },
      {
        name: "Eldercare",
        tags: [
          { name: "Companionship" },
          { name: "CPR training" },
          { name: "Errands" },
          { name: "First aid training" },
          { name: "Homework help" },
          { name: "Infant care" },
          { name: "Light housekeeping" },
          { name: " Live-in care" },
          { name: "Live-out care" },
          { name: "Meal preparation" },
          { name: "Mobility support" },
          { name: "Newborn care" },
          { name: "Overnight sitting" },
          { name: "Personal care (e.g washing, dressing)" },
          { name: "Pick up / Drop off" },
          { name: " Shopping" },
          { name: " Virtual Care" },
        ],
      },
      {
        name: "Nursing",
        tags: [
          { name: "Companionship" },
          { name: "CPR training" },
          { name: "Errands" },
          { name: "First aid training" },
          { name: "Homework help" },
          { name: "Infant care" },
          { name: "Light housekeeping" },
          { name: " Live-in care" },
          { name: "Live-out care" },
          { name: "Meal preparation" },
          { name: "Mobility support" },
          { name: "Newborn care" },
          { name: "Overnight sitting" },
          { name: "Personal care (e.g washing, dressing)" },
          { name: "Pick up / Drop off" },
          { name: " Shopping" },
          { name: " Virtual Care" },
        ],
      },
      {
        name: "Housekeeping",
        tags: [
          { name: "Bed changing" },
          { name: "Dish washing" },
          { name: "Furniture cleaning" },
          { name: "Floor cleaning" },
          { name: "Grocery shopping" },
          { name: "House sitting" },
          { name: "Ironing" },
          { name: "Laundry" },
          { name: "Moving help" },
          { name: "Oven cleaning" },
          { name: " Plant watering" },
          { name: "Refrigerator cleaning" },
          { name: "Snow removal" },
          { name: "Window cleaning" },
          { name: "Closet organizer" },
          { name: "Carpet cleaning" },
          { name: "Junk removal" },
        ],
      },
      {
        name: "Transport & Shuttle",
        tags: [
          { name: "Mobility support" },
          { name: "Daily shuttle" },
          { name: "Assisted transportation" },
          { name: "Senior transportation" },
          { name: "Door-to-door" },
          { name: "Shared ride" },
          { name: "Airport shuttle" },
        ],
      },
      {
        name: "Petsitter",
        tags: [
          { name: "Dogs" },
          { name: "Cats" },
          { name: "Fish" },
          { name: "Birds" },
          { name: "Pet" },
          { name: "Exotic pets" },
          { name: "Horses" },
          { name: "Pet Daycare" },
          { name: "Overnight sitting" },
          { name: "Pet boarding " },
          { name: "Pet feeding" },
          { name: "Pet grooming" },
          { name: "Pet training" },
          { name: "Pet transportation" },
          { name: "Pet walking" },
        ],
      },
    ],
  },

  {
    name: "Moving, Maintenance & Repair",
    subCategories: [
      {
        name: "Electrical & Appliances",
        tags: [
          { name: "Ceiling Fan" },
          { name: "Circuit Breaker" },
          { name: "Dishwasher" },
          { name: "Dryer" },
          { name: "Electrical wiring" },
          { name: "Electrical switches" },
          { name: "outlets & fixtures" },
          { name: "Freezer" },
          { name: "Microwave" },
          { name: "Refrigerator" },
          { name: "Smart security cam" },
          { name: "Smart thermostat" },
          { name: "Smoke detector" },
          { name: "Heating system" },
          { name: "Install" },
          { name: "Replace" },
          { name: "Repair" },
          { name: "Small appliances" },
          { name: "Washing machine" },
          { name: "Lighting" },
          { name: "Security" },
          { name: "Doorbell" },
          { name: "Smart devices" },
          { name: "Vacuum cleaner" },
          { name: "Computer " },
        ],
      },
      {
        name: "Plumbing",
        tags: [
          { name: "Bathtube" },
          { name: "Drain" },
          { name: "Faucet" },
          { name: "Garbage Disposal" },
          { name: "Pipe" },
          { name: "Pump" },
          { name: "Sink" },
          { name: "Shower" },
          { name: "Sprinkler systems" },
          { name: "Toilet" },
          { name: "Valve" },
          { name: "Water heater. Install" },
          { name: "Replace" },
          { name: "Repair" },
          { name: "Kitchen" },
          { name: "Bathroom" },
          { name: "Garden" },
        ],
      },
      {
        name: "Heating  & Cooling",
        tags: [
          { name: "Furnace repair & maintenance" },
          { name: "Air conditioning repair & maintenance" },
          { name: "Hot water tank repair" },
          { name: "Boiler repair" },
          { name: "Heating system" },
          { name: "Isolation" },
          { name: "Window isolation" },
          { name: "Door isolation" },
          { name: "Solar cells" },
          { name: "Solar energy" },
        ],
      },
      {
        name: "Gardening",
        tags: [
          { name: "Fall & Spring clean ups" },
          { name: "Grass cutting" },
          { name: "Hedge trimming" },
          { name: "Mulching" },
          { name: "Garden design" },
          { name: "Gardening" },
          { name: "Garden architecture" },
          { name: "Indoor gardening" },
          { name: "Landscaping" },
          { name: "Lawn care" },
          { name: "Lawn fertilizing" },
          { name: "Leaf removal" },
          { name: "Planting" },
          { name: "Seeding" },
          { name: "Snow removal" },
          { name: "Sod installation" },
          { name: "Tree trimming" },
          { name: "Tree removal" },
          { name: "Urban gardening" },
          { name: "Vegetable garden" },
          { name: "Weeding," },
        ],
      },
      {
        name: "Mechanics",
        tags: [
          { name: "Pkw" },
          { name: "Lkw" },
          { name: "Car" },
          { name: "Vans" },
          { name: "Bikes" },
          { name: "Motorbikes" },
          { name: "Trucks" },
          { name: "Tractor" },
          { name: "BMW" },
          { name: "Audi" },
          { name: "Volkswagen" },
          { name: "Seat" },
          { name: "Porsche" },
          { name: "Ford" },
          { name: "Fiat" },
          { name: "Renault" },
          { name: "Peugeot" },
          { name: "Mini cooper" },
          { name: "Jaguar" },
          { name: "Tesla" },
          { name: "Hybrid" },
          { name: "Combustion Engine" },
          { name: "Electric car" },
          { name: "Car accident" },
          { name: "Heating & AC" },
          { name: "Brakes" },
          { name: "Electronics" },
          { name: "Glass repair" },
          { name: "Inspection" },
          { name: "Hail damage" },
          { name: "Tires" },
          { name: "Oil" },
          { name: "Engine" },
          { name: "HU/AU" },
          { name: "Battery" },
          { name: "Belts" },
          { name: "Clutch & Transmission" },
          { name: "Diagnostics" },
          { name: "Doors" },
          { name: "Exhaust System" },
          { name: "Filters" },
          { name: "Fluids" },
          { name: "Fuel System" },
          { name: "Hoses" },
          { name: "Ignition" },
          { name: "Lights" },
          { name: "Mirrors" },
          { name: "Sensors" },
          { name: "Suspension & Steering" },
          { name: "Switches" },
          { name: "Windows" },
          { name: "Wiper" },
        ],
      },
      {
        name: "Pest Control",
        tags: [
          { name: "Ants" },
          { name: "Carpenter Ants" },
          { name: "Termite Control" },
          { name: "Termite Inspection" },
          { name: "Bats" },
          { name: "Bees" },
          { name: "Bed Bugs" },
          { name: "Cockroaches" },
          { name: "Fleas" },
          { name: "Tick" },
          { name: "Spiders" },
          { name: "Wasps" },
          { name: "Mice & Rat" },
        ],
      },
      {
        name: "Security",
        tags: [
          { name: "Indoor camera" },
          { name: "Outdoor camera" },
          { name: "Smart home controller" },
          { name: "Home security system" },
          { name: "Doorbell" },
          { name: "Doors lock" },
          { name: "Windows lock" },
          { name: "Guardian services" },
          { name: "Smoke alarms" },
        ],
      },
      {
        name: "Carpentry",
        tags: [
          { name: "Built in furniture" },
          { name: "Cabinets & Countertops" },
          { name: "Closets" },
          { name: "Decks" },
          { name: "Fences & ramps" },
          { name: "Doors" },
          { name: "Fine carpentry" },
          { name: "Finish carpentry" },
          { name: "trim & molding" },
          { name: "Framing" },
          { name: "Siding" },
          { name: "Gutters & Exterior Trim" },
          { name: "Stairs & railings. " },
        ],
      },
      {
        name: "Painting & Staining",
        tags: [
          { name: "Ceilings" },
          { name: "Exterior painting" },
          { name: "Doors" },
          { name: "Fences" },
          { name: "Interior painting" },
          { name: "Paint removal & cleaning" },
          { name: "Scrapping" },
          { name: "Staining" },
          { name: "Wallpapering" },
          { name: "Walls. " },
        ],
      },
      {
        name: "Windows, Doors & Locks",
        tags: [
          { name: "Sliding door or tracks" },
          { name: "Window blind" },
          { name: "Window cleaning" },
          { name: "Window curtain" },
          { name: "Window drapery" },
          { name: "Window shade" },
          { name: "Window treatment. Install" },
          { name: "Replace" },
          { name: "Repair." },
        ],
      },
      {
        name: "Floors",
        tags: [
          { name: "Carpet" },
          { name: "Hardwood" },
          { name: "Brick & stone" },
          { name: "Concrete" },
          { name: "Laminate & vinyl" },
          { name: "Tile" },
        ],
      },
      {
        name: "Moving services",
        tags: [
          { name: "Furniture assembly" },
          { name: "Furniture disassenbly" },
          { name: "Hanging pictures & shelves" },
          { name: "Move In cleaning" },
          { name: "Move out cleaning" },
          { name: "Moving help" },
          { name: "Storage" },
          { name: "TV Mounting" },
          { name: "Moving transportation" },
          { name: "Packaging" },
          { name: "Install" },
          { name: "Painting" },
          { name: "Heavy furniture" },
          { name: "Domestic moving" },
          { name: "International moving" },
        ],
      },
    ],
  },
  {
    name: "Writing & Translation",
    subCategories: [
      {
        name: "Translation",
        tags: [
          { name: "Interpreter" },
          { name: "Legal translation" },
          { name: "Medical translation" },
          { name: "Technical translation" },
          { name: "Translation German - Spanish" },
          { name: "Translation English - Spanish" },
          { name: "Translation German - English" },
          { name: "Translation German - Russian" },
          { name: " Translation English- Russian" },
          { name: "Translation German - Arabic" },
          { name: "Translation English  - Arabic" },
          { name: "Translation German - French" },
          { name: " Translation  English - French" },
          { name: " Translation German - Italian" },
          { name: "Translation English - Italian" },
          { name: "Translation German - Chinese" },
          { name: "Translation English - Chinese" },
          { name: "Translation German - Dutch" },
          { name: "Translation English  - Dutch" },
          { name: "Translation German - Hindi" },
          { name: "Translation English - Hindi" },
          { name: "Translation German - Korean" },
          {
            name: "Translation English - Korean,Translation German - Japanese",
          },
          { name: "Translation English- Japanese" },
          { name: "Translation German - Polish" },
          { name: " Translation English - Polish" },
          { name: "Translation German - Portuguese" },
          { name: "Translation English - Portuguese" },
          { name: "Translation German - Thai" },
          { name: "Translation English  - Thai" },
          { name: " Translation German -Turkish" },
          { name: "Translation German - English" },
          { name: "Translation German - Ukrainian" },
          { name: "Translation  English - Ukrainian" },
        ],
      },
      {
        name: "Writing",
        tags: [
          { name: "Blog Writing" },
          { name: "Business writing" },
          { name: "Content writing" },
          { name: " Cover letter writing" },
          { name: "Copywriting" },
          { name: "Creative writing" },
          { name: "Ghostwriting" },
          { name: "Editing & Proofreading" },
          { name: "Resume writing" },
          { name: "Technical writing" },
          { name: "Speach writing" },
          { name: "Plagiarism report" },
          { name: "Essay writing" },
          { name: "Disertation writing" },
          { name: "Thesis writing" },
          { name: "PowerPoint presentations" },
        ],
      },
    ],
  },
  {
    name: "Marketing, Design & Creative",
    subCategories: [
      {
        name: "Design & Creative",
        tags: [
          { name: " Animation" },
          { name: "Rendering" },
          { name: "Audio production" },
          { name: "Audio editing" },
          { name: "Brand design" },
          { name: "Editorial design" },
          { name: "Exhibit design" },
          { name: "Fashion design" },
          { name: "Graphic design" },
          { name: "Ilustration" },
          { name: "Image editing/retouching" },
          { name: "Musician" },
          { name: "Photography" },
          { name: "Presentation Design" },
          { name: "Scriptwriting" },
          { name: "Social Media strategy" },
          { name: "Video editing" },
          { name: "Video production" },
          { name: "Vocalist" },
          { name: "Voice talent" },
        ],
      },
      {
        name: "Marketing",
        tags: [
          { name: " Campaign management" },
          { name: "Comunity management" },
          { name: "Content strategy" },
          { name: "Digital marketing" },
          { name: "Email marketing" },
          { name: "Lead generation" },
          { name: "Marketing consulting" },
          { name: "Market research" },
          { name: "Marketing strategy" },
          { name: "SEO" },
          { name: "SEM" },
          { name: "Social media marketing" },
          { name: "Telemarketing" },
        ],
      },
    ],
  },
  {
    name: "IT & Development",
    subCategories: [
      {
        name: "IT & Development",
        tags: [
          { name: "Mobile development" },
          { name: "Web development" },
          { name: "UI & UX Design" },
          { name: "Full Stack" },
          { name: "Data science" },
          { name: "Application development" },
          { name: "Back-end development" },
          { name: "Cybersecurity" },
          { name: "IT support" },
          { name: "IT compliance" },
          { name: "Cloud engineering" },
          { name: "Software Engineering" },
          { name: "Coding tutoring" },
          { name: "Automation testing" },
          { name: "AR/VR development" },
          { name: "Database development" },
          { name: "eCommerce development" },
          { name: "Fimrware development" },
          { name: "Front-end development" },
          { name: "Manual testing" },
          { name: "Mobile design" },
          { name: "Prototyping" },
          { name: "Scripting & Automation" },
          { name: "Web design " },
        ],
      },
    ],
  },
  {
    name: "Accounting, Legal & Consulting",
    subCategories: [
      {
        name: "Accounting",
        tags: [
          { name: "Accounting" },
          { name: "Bookkeeping" },
          { name: "Business analysis" },
          { name: "Financial analysis" },
          { name: "Tax consultant" },
          { name: "Tax preparation." },
        ],
      },
      {
        name: "Legal",
        tags: [
          { name: "Labor / employment law" },
          { name: "Legal services" },
          { name: "Inmigration law" },
          { name: "Intelectual property Law" },
          { name: "Tax law" },
          { name: "Contracts" },
        ],
      },
      {
        name: "Consulting",
        tags: [
          { name: "Anmeldung registration" },
          { name: "Arbeitsagentur application" },
          { name: "Bureaucracy assistance" },
          { name: " Conversion of drivers license" },
          { name: " Insurance" },
          { name: "Mediation" },
          { name: "Rental contracts review" },
          { name: " Visa preparation" },
          { name: "Contracts" },
        ],
      },
    ],
  },
];

/*const string =
  "Accounting, Legal & Consulting%Accounting!Accounting, Bookkeeping, Business analysis, Financial analysis, Tax consultant, Tax preparation.!Legal!Labor / employment law, Legal services, Inmigration law, Intelectual property Law, Tax law, Contracts!Consulting!Anmeldung registration, Arbeitsagentur application, Bureaucracy assistance,  Conversion of drivers license,  Insurance, Mediation, Rental contracts review,  Visa preparation, Contracts";

const [category, subcategoryString] = string.split("%").filter((x) => x !== "");
const subcategories = subcategoryString
  .split("!")
  .filter((x) => x !== "")
  .filter((x, i) => i % 2 === 0);
const tags = subcategoryString
  .split("!")
  .filter((x) => x !== "")
  .filter((x, i) => i % 2 === 1);

const parseTags = tagsString => {
  const _tags = tagsString.split(", ");

  const generateTagCode = (name) => `{name: "${name}"}`;

  const tagsCode = _tags.map(generateTagCode);
  return  tagsCode.join(",");
}

const final = `{
  name: "${category}",
  subCategories: [
    ${subcategories.map((s, i) => {
      return `{
        name: "${s}",
        tags: [
          ${parseTags(tags[i])}
        ]
      }
      `
    })}
  ]
}`

console.log(final)*/
